version: '3.9'

services:
  web:
    image: web_image
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./media:/app/hackzurich/media
    ports:
      - "8000:8000"
    # env_file:
    #   - ./.env.dev