# Generated by Django 4.1.1 on 2022-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='link',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
