# Generated by Django 4.1.1 on 2022-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_good_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('о', 'Другое')], default='m', max_length=1),
        ),
    ]
