# Generated by Django 4.1.1 on 2022-09-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_silhouette_alter_good_img_good_silhouette_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='img',
            new_name='image_url',
        ),
    ]
