# Generated by Django 4.1.1 on 2022-09-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_brand_name_alter_category_name_alter_good_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('u', 'Унисекс')], default='m', max_length=1),
        ),
    ]
